[project]
name = "wr-premier"
dynamic = ["version"]
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
    "keboola-component>=1.9.0",
    "keboola-http-client>=1.0.1",
    "keboola-utils>=1.1.0",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "keboola.datadirtest>=2.0.0",
    "pytest>=9.0.2",
    "responses>=0.25.0",
    "ruff>=0.15.2",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I", "UP", "G"]
